### ISSUE TITLE
结构BOM表问题-SHR1.0MM双头连接线10P修改为7P

### ISSUE THREAD

**Issue by qxzg** [ZhaJiHu/Cubli_Mini#7]
1. `结构bom.xls`中第24行的`SHR1.0MM双头连接线 10P`线应该改为`7p`吧，我看pcb文件里控制板和AS5600之间的连接用的是7pin的连接座，没有看到10pin的。
2. 另外14-17行中的`M2.5 D4通孔铝柱_2x12mm`里的`_2`是不是是多余的啊。

**Comment by ZhaJiHu** [comment]
SHR1.0MM双头连接线 没有10P的，只有7P的

**Comment by ZhaJiHu** [comment]
麻烦新建一个分支，命名为：#7，推送上来再提交merge request

**Comment by ZhaJiHu** [comment]
已经merge
